name: Sort Links

on:
  push:
    branches:
      - main
      
jobs:
  CI:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pnpm-version: [10]
        node-version: [22]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Prepare pnpm ${{matrix.pnpm-version}}
        uses: pnpm/action-setup@v4
        with:
          version: ${{matrix.pnpm-version}}
      - name: Prepare Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node-version}}
      - name: Cache node_modules
        uses: actions/cache@v4
        env:
          cache-name: project-node-modules
        with:
          path: node_modules
          key: ${{runner.os}}-${{env.cache-name}}-${{hashFiles('package.json')}}
      - name: Install dependencies
        run: pnpm install
      - name: Run sort script
        run: pnpm tsx sort.ts
      - name: Commit and push
        run: |
          git config --local user.email "148861329+inslicc@users.noreply.github.com"
          git config --local user.name "inslicc"
          git add -A
          git diff --staged --quiet || git commit -m "chore: auto-sort YAML file"
          git push